-- EduMatch — esquema PostgreSQL para Supabase
-- La autenticación de contraseña vive en auth.users (Supabase Auth).
-- Las tablas públicas contienen exclusivamente datos de aplicación.

create extension if not exists pgcrypto;

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  correo text not null,
  rol text not null check (rol in ('Estudiante','Tutor')),
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.materias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  categoria text not null default 'General',
  descripcion text,
  creada_por uuid references public.perfiles(id) on delete set null,
  creada_en timestamptz not null default now()
);

create table if not exists public.tutor_materias (
  tutor_id uuid not null references public.perfiles(id) on delete cascade,
  materia_id bigint not null references public.materias(id) on delete cascade,
  primary key (tutor_id, materia_id)
);

do $$
begin
  create type public.estado_solicitud as enum (
    'pendiente',
    'aceptada',
    'rechazada',
    'propuesta_horario',
    'cancelada',
    'realizada'
  );
exception
  when duplicate_object then null;
end $$;

create table if not exists public.solicitudes_tutoria (
  id bigint primary key,
  estudiante_id uuid not null references public.perfiles(id) on delete restrict,
  tutor_id uuid references public.perfiles(id) on delete set null,
  materia_id bigint not null references public.materias(id) on delete restrict,
  fecha_preferida date not null,
  hora_preferida time not null,
  tema text,
  estado public.estado_solicitud not null default 'pendiente',
  fecha_propuesta date,
  hora_propuesta time,
  mensaje_propuesta text,
  tutores_rechazados uuid[] not null default '{}',
  origen_rechazo text,
  fecha_propuesta_rechazada date,
  hora_propuesta_rechazada time,
  motivo_cancelacion text,
  abierta_reasignacion boolean not null default false,
  oculta_para_estudiante boolean not null default false,
  oculta_para_tutor boolean not null default false,
  respondida_en timestamptz,
  realizada_en timestamptz,
  creada_en timestamptz not null default now(),
  actualizada_en timestamptz not null default now()
);

create table if not exists public.historial_solicitud (
  id bigint generated by default as identity primary key,
  solicitud_id bigint not null references public.solicitudes_tutoria(id) on delete cascade,
  tipo text not null,
  fecha_evento timestamptz not null default now(),
  detalles jsonb not null default '{}'::jsonb
);

create table if not exists public.calificaciones (
  solicitud_id bigint primary key references public.solicitudes_tutoria(id) on delete cascade,
  estudiante_id uuid not null references public.perfiles(id) on delete restrict,
  tutor_id uuid references public.perfiles(id) on delete set null,
  puntuacion smallint not null check (puntuacion between 1 and 5),
  comentario text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists idx_perfiles_rol_activo on public.perfiles(rol, activo);
create index if not exists idx_tutor_materias_materia on public.tutor_materias(materia_id);
create index if not exists idx_solicitudes_estudiante on public.solicitudes_tutoria(estudiante_id, creada_en desc);
create index if not exists idx_solicitudes_tutor on public.solicitudes_tutoria(tutor_id, creada_en desc);
create index if not exists idx_solicitudes_materia_estado on public.solicitudes_tutoria(materia_id, estado);
create index if not exists idx_historial_solicitud on public.historial_solicitud(solicitud_id, fecha_evento);

-- Crea automáticamente el perfil de aplicación cuando Supabase Auth registra una cuenta.
create or replace function public.crear_perfil_desde_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfiles (id, nombre, correo, rol)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nombre', 'Usuario'),
    coalesce(new.email, ''),
    case when coalesce(new.raw_user_meta_data ->> 'rol', 'Estudiante') = 'Tutor' then 'Tutor' else 'Estudiante' end
  )
  on conflict (id) do update
    set nombre = excluded.nombre,
        correo = excluded.correo,
        rol = excluded.rol,
        activo = true;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_edumatch on auth.users;
create trigger on_auth_user_created_edumatch
after insert on auth.users
for each row execute procedure public.crear_perfil_desde_auth();

create or replace function public.actualizar_timestamp_edumatch()
returns trigger
language plpgsql
as $$
begin
  new.actualizada_en = now();
  return new;
end;
$$;

drop trigger if exists solicitudes_tutoria_actualizada_en on public.solicitudes_tutoria;
create trigger solicitudes_tutoria_actualizada_en
before update on public.solicitudes_tutoria
for each row execute procedure public.actualizar_timestamp_edumatch();

create or replace function public.actualizar_timestamp_calificacion()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

drop trigger if exists calificaciones_actualizado_en on public.calificaciones;
create trigger calificaciones_actualizado_en
before update on public.calificaciones
for each row execute procedure public.actualizar_timestamp_calificacion();

-- RLS
alter table public.perfiles enable row level security;
alter table public.materias enable row level security;
alter table public.tutor_materias enable row level security;
alter table public.solicitudes_tutoria enable row level security;
alter table public.historial_solicitud enable row level security;
alter table public.calificaciones enable row level security;

drop policy if exists perfiles_select_public on public.perfiles;
create policy perfiles_select_public on public.perfiles
for select to anon, authenticated using (activo = true);

drop policy if exists perfiles_update_own on public.perfiles;
create policy perfiles_update_own on public.perfiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists materias_select_public on public.materias;
create policy materias_select_public on public.materias
for select to anon, authenticated using (true);

drop policy if exists materias_insert_auth on public.materias;
create policy materias_insert_auth on public.materias
for insert to authenticated with check (creada_por = auth.uid() or creada_por is null);

drop policy if exists materias_update_creator on public.materias;
create policy materias_update_creator on public.materias
for update to authenticated using (creada_por = auth.uid()) with check (creada_por = auth.uid());

drop policy if exists tutor_materias_select_public on public.tutor_materias;
create policy tutor_materias_select_public on public.tutor_materias
for select to anon, authenticated using (true);

drop policy if exists tutor_materias_insert_own on public.tutor_materias;
create policy tutor_materias_insert_own on public.tutor_materias
for insert to authenticated with check (tutor_id = auth.uid());

drop policy if exists tutor_materias_delete_own on public.tutor_materias;
create policy tutor_materias_delete_own on public.tutor_materias
for delete to authenticated using (tutor_id = auth.uid());

drop policy if exists solicitudes_select_partes on public.solicitudes_tutoria;
create policy solicitudes_select_partes on public.solicitudes_tutoria
for select to authenticated using (estudiante_id = auth.uid() or tutor_id = auth.uid());

drop policy if exists solicitudes_insert_estudiante on public.solicitudes_tutoria;
create policy solicitudes_insert_estudiante on public.solicitudes_tutoria
for insert to authenticated with check (estudiante_id = auth.uid());

create or replace function public.validar_modificacion_solicitud()
returns trigger
language plpgsql
security invoker
as $$
begin
  if auth.uid() is null then
    raise exception 'Usuario no autenticado';
  end if;

  if auth.uid() <> old.estudiante_id and (old.tutor_id is null or auth.uid() <> old.tutor_id) then
    raise exception 'No autorizado para modificar esta solicitud';
  end if;

  if new.id <> old.id or new.estudiante_id <> old.estudiante_id or new.materia_id <> old.materia_id then
    raise exception 'No se pueden cambiar el identificador, estudiante o materia de una solicitud';
  end if;

  return new;
end;
$$;

drop trigger if exists validar_modificacion_solicitud_edumatch on public.solicitudes_tutoria;
create trigger validar_modificacion_solicitud_edumatch
before update on public.solicitudes_tutoria
for each row execute procedure public.validar_modificacion_solicitud();

drop policy if exists solicitudes_update_partes on public.solicitudes_tutoria;
create policy solicitudes_update_partes on public.solicitudes_tutoria
for update to authenticated
using (estudiante_id = auth.uid() or tutor_id = auth.uid())
with check (true);

drop policy if exists historial_select_partes on public.historial_solicitud;
create policy historial_select_partes on public.historial_solicitud
for select to authenticated using (
  exists (
    select 1 from public.solicitudes_tutoria s
    where s.id = historial_solicitud.solicitud_id
      and (s.estudiante_id = auth.uid() or s.tutor_id = auth.uid())
  )
);

drop policy if exists historial_insert_partes on public.historial_solicitud;
create policy historial_insert_partes on public.historial_solicitud
for insert to authenticated with check (
  exists (
    select 1 from public.solicitudes_tutoria s
    where s.id = historial_solicitud.solicitud_id
      and (s.estudiante_id = auth.uid() or s.tutor_id = auth.uid())
  )
);

drop policy if exists historial_delete_partes on public.historial_solicitud;
create policy historial_delete_partes on public.historial_solicitud
for delete to authenticated using (
  exists (
    select 1 from public.solicitudes_tutoria s
    where s.id = historial_solicitud.solicitud_id
      and (s.estudiante_id = auth.uid() or s.tutor_id = auth.uid())
  )
);

drop policy if exists calificaciones_select_partes on public.calificaciones;
create policy calificaciones_select_partes on public.calificaciones
for select to authenticated using (estudiante_id = auth.uid() or tutor_id = auth.uid());

drop policy if exists calificaciones_insert_estudiante on public.calificaciones;
create policy calificaciones_insert_estudiante on public.calificaciones
for insert to authenticated with check (estudiante_id = auth.uid());

drop policy if exists calificaciones_update_estudiante on public.calificaciones;
create policy calificaciones_update_estudiante on public.calificaciones
for update to authenticated using (estudiante_id = auth.uid()) with check (estudiante_id = auth.uid());

drop policy if exists calificaciones_delete_estudiante on public.calificaciones;
create policy calificaciones_delete_estudiante on public.calificaciones
for delete to authenticated using (estudiante_id = auth.uid());

-- Permisos explícitos para la Data API.
grant select on public.perfiles, public.materias, public.tutor_materias to anon, authenticated;
grant update on public.perfiles to authenticated;
grant insert, update on public.materias to authenticated;
grant insert, delete on public.tutor_materias to authenticated;
grant select, insert, update on public.solicitudes_tutoria to authenticated;
grant select, insert, delete on public.historial_solicitud to authenticated;
grant select, insert, update, delete on public.calificaciones to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.perfiles;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.materias;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.tutor_materias;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.solicitudes_tutoria;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.historial_solicitud;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.calificaciones;
exception when duplicate_object then null;
end $$;

-- Catálogo oficial del MVP (APP-03).
insert into public.materias (id, nombre, categoria, descripcion) values
(1, 'Cálculo Diferencial', 'Matemáticas', 'Límites, derivadas, optimización y sus aplicaciones en ingeniería.'),
(2, 'Programación Orientada a Objetos', 'Sistemas', 'Clases, objetos, herencia, polimorfismo y patrones de diseño.'),
(3, 'Física Mecánica', 'Física', 'Leyes de Newton, conservación de la energía, momento y cinemática.'),
(4, 'Estructuras de Datos', 'Sistemas', 'Listas enlazadas, árboles binarios, grafos y análisis de algoritmos.'),
(5, 'Álgebra Lineal', 'Matemáticas', 'Vectores, matrices, espacios vectoriales y transformaciones lineales.'),
(6, 'Bases de Datos', 'Sistemas', 'Modelado relacional, SQL, normalización y gestión de datos.')
on conflict (id) do update set
  nombre = excluded.nombre,
  categoria = excluded.categoria,
  descripcion = excluded.descripcion;

select setval(pg_get_serial_sequence('public.materias','id'), greatest(coalesce((select max(id) from public.materias), 1), 1));
